export const UPDATE_ROOMS_LIST = 'UPDATE_ROOMS_LIST';
export const FETCH_ROOMS_LIST = 'FETCH_ROOMS_LIST';

export const REQUEST_POST_ROOM = 'REQUEST_POST_ROOM';
export const ADD_ROOM_TO_LIST = 'ADD_ROOM_TO_LIST';
