export const UPDATE_MESSAGES = 'UPDATE_MESSAGES';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const MESSAGE_INCOMING = 'MESSAGE_INCOMING';
export const SET_MY_USERNAME = 'SET_MY_USERNAME';
